### ISSUE TITLE
Window.get_active() retuns Null on RaspberryPi (Raspbian)

### ISSUE THREAD

**Issue by yurikleb** [antocuni/wmctrl#13]
My code works well on Ubuntu, however when moving to raspbian (arm64 bullseye on a RasberyPi 4)
`Window.get_active()` returns Null.

Other commands such as `Window.list()` work well so as a workaround I'm using:
`my_window = Window.by_name("pi@raspberrypi: ~/my_project")[0]`
But this requires hardcoding the window name.

**Comment by antocuni** [comment]
`Window.get_active()` is implemented by calling `xprop`:
https://github.com/antocuni/wmctrl/blob/91a2cdc3b1ab8e9800dc61bd89891aba4d964d93/wmctrl.py#L129-L132

is it possible that on your raspian `xprop` is not installed?

**Comment by yurikleb** [comment]
Good point!
It does seem like Raspbian does not have `wmctrl` or `xprop` installed by default.
on Ubuntu I only had to install `wmctrl`.

It works now after installing x11-utils via `apt-get install x11-utils` and wmctrl via `apt-get install wmctrl`

Thanks for the quick response!
